export declare const STORE_ACTION = "STORE_ACTION";
export declare const SELECTOR_SUBSCRIPTION = "SELECTOR_SUBSCRIPTION";
export declare const SELECTOR_UNSUBSCRIPTION = "SELECTOR_UNSUBSCRIPTION";
export declare const SELECTOR_RESULT = "SELECTOR_RESULT";
