export const STORE_ACTION = 'STORE_ACTION';
export const SELECTOR_SUBSCRIPTION = 'SELECTOR_SUBSCRIPTION';
export const SELECTOR_UNSUBSCRIPTION = 'SELECTOR_UNSUBSCRIPTION';
export const SELECTOR_RESULT = 'SELECTOR_RESULT';